import type { IExerciseDetail } from "./interfaces/exerciseDb/IExerciseDetail";

export const mockExercises: IExerciseDetail[] = [
  {
    exerciseId: "exr_001",
    name: "Barbell Bench Press",
    imageUrl: "https://cdn.exercisedb.dev/media/w/images/bench-press.jpg",
    imageUrls: {
      "360p": "https://cdn.exercisedb.dev/media/w/images/bench-press-360.jpg",
      "720p": "https://cdn.exercisedb.dev/media/w/images/bench-press-720.jpg",
    },
    equipments: ["Barbell", "Flat Bench"],
    bodyParts: ["CHEST"],
    exerciseType: "Strength",
    targetMuscles: ["PECTORALIS MAJOR"],
    secondaryMuscles: ["TRICEPS", "ANTERIOR DELTOID"],
    videoUrl: "https://cdn.exercisedb.dev/w/videos/bench-press.mp4",
    keywords: ["bench", "press", "chest", "barbell"],
    overview:
      "The Barbell Bench Press is a compound upper body exercise that primarily targets the chest muscles while also engaging the triceps and shoulders.",
    instructions: [
      "Lie flat on a bench with your feet firmly on the ground.",
      "Grip the barbell slightly wider than shoulder-width apart.",
      "Unrack the bar and lower it slowly to your mid-chest.",
      "Press the bar back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    exerciseTips: [
      "Keep your shoulder blades retracted throughout the movement.",
      "Avoid flaring your elbows excessively.",
      "Maintain a slight arch in your lower back.",
    ],
    variations: ["Incline Bench Press", "Dumbbell Bench Press", "Close-Grip Bench Press"],
    relatedExerciseIds: ["exr_002", "exr_003"],
  },
  {
    exerciseId: "exr_002",
    name: "Barbell Back Squat",
    imageUrl: "https://cdn.exercisedb.dev/media/w/images/back-squat.jpg",
    imageUrls: {
      "360p": "https://cdn.exercisedb.dev/media/w/images/back-squat-360.jpg",
      "720p": "https://cdn.exercisedb.dev/media/w/images/back-squat-720.jpg",
    },
    equipments: ["Barbell", "Squat Rack"],
    bodyParts: ["QUADRICEPS", "THIGHS"],
    exerciseType: "Strength",
    targetMuscles: ["QUADRICEPS"],
    secondaryMuscles: ["GLUTEUS MAXIMUS", "HAMSTRINGS", "ERECTOR SPINAE"],
    videoUrl: "https://cdn.exercisedb.dev/w/videos/back-squat.mp4",
    keywords: ["squat", "legs", "barbell", "compound"],
    overview:
      "The Barbell Back Squat is a fundamental compound exercise that targets the quadriceps, glutes, and hamstrings, building overall lower body strength.",
    instructions: [
      "Position the barbell on your upper traps and unrack it.",
      "Stand with feet shoulder-width apart, toes slightly pointed out.",
      "Bend at the hips and knees, lowering until your thighs are parallel to the floor.",
      "Drive through your heels to return to standing.",
      "Repeat for the desired number of repetitions.",
    ],
    exerciseTips: [
      "Keep your chest up and core braced throughout.",
      "Do not let your knees cave inward.",
      "Control the descent to maintain tension on the muscles.",
    ],
    variations: ["Front Squat", "Goblet Squat", "Bulgarian Split Squat"],
    relatedExerciseIds: ["exr_004", "exr_005"],
  },
  {
    exerciseId: "exr_003",
    name: "Deadlift",
    imageUrl: "https://cdn.exercisedb.dev/media/w/images/deadlift.jpg",
    imageUrls: {
      "360p": "https://cdn.exercisedb.dev/media/w/images/deadlift-360.jpg",
      "720p": "https://cdn.exercisedb.dev/media/w/images/deadlift-720.jpg",
    },
    equipments: ["Barbell"],
    bodyParts: ["BACK", "HAMSTRINGS"],
    exerciseType: "Strength",
    targetMuscles: ["ERECTOR SPINAE", "GLUTEUS MAXIMUS"],
    secondaryMuscles: ["HAMSTRINGS", "TRAPEZIUS", "FOREARMS"],
    videoUrl: "https://cdn.exercisedb.dev/w/videos/deadlift.mp4",
    keywords: ["deadlift", "back", "posterior chain", "barbell"],
    overview:
      "The Deadlift is a full-body compound exercise that primarily targets the posterior chain, including the back, glutes, and hamstrings.",
    instructions: [
      "Stand with feet hip-width apart, barbell over mid-foot.",
      "Hinge at the hips and grip the bar just outside your knees.",
      "Brace your core and lift the bar by extending your hips and knees.",
      "Stand tall at the top with shoulders back.",
      "Lower the bar back to the floor with control.",
    ],
    exerciseTips: [
      "Keep the bar close to your body throughout the lift.",
      "Do not round your lower back.",
      "Engage your lats before initiating the pull.",
    ],
    variations: ["Romanian Deadlift", "Sumo Deadlift", "Trap Bar Deadlift"],
    relatedExerciseIds: ["exr_002", "exr_005"],
  },
  {
    exerciseId: "exr_004",
    name: "Pull-Up",
    imageUrl: "https://cdn.exercisedb.dev/media/w/images/pull-up.jpg",
    imageUrls: {
      "360p": "https://cdn.exercisedb.dev/media/w/images/pull-up-360.jpg",
      "720p": "https://cdn.exercisedb.dev/media/w/images/pull-up-720.jpg",
    },
    equipments: ["Pull-Up Bar"],
    bodyParts: ["BACK"],
    exerciseType: "Strength",
    targetMuscles: ["LATISSIMUS DORSI"],
    secondaryMuscles: ["BICEPS", "RHOMBOIDS", "REAR DELTOID"],
    videoUrl: "https://cdn.exercisedb.dev/w/videos/pull-up.mp4",
    keywords: ["pull-up", "back", "bodyweight", "lats"],
    overview:
      "The Pull-Up is a bodyweight exercise that primarily targets the latissimus dorsi, building upper body pulling strength and back width.",
    instructions: [
      "Hang from a pull-up bar with an overhand grip, hands shoulder-width apart.",
      "Engage your core and pull your body up until your chin is above the bar.",
      "Pause briefly at the top.",
      "Lower yourself back down with control to full arm extension.",
      "Repeat for the desired number of repetitions.",
    ],
    exerciseTips: [
      "Avoid using momentum or swinging.",
      "Focus on pulling with your elbows, not your hands.",
      "If needed, use a resistance band for assistance.",
    ],
    variations: ["Chin-Up", "Wide-Grip Pull-Up", "Weighted Pull-Up"],
    relatedExerciseIds: ["exr_003", "exr_006"],
  },
  {
    exerciseId: "exr_005",
    name: "Overhead Press",
    imageUrl: "https://cdn.exercisedb.dev/media/w/images/overhead-press.jpg",
    imageUrls: {
      "360p": "https://cdn.exercisedb.dev/media/w/images/overhead-press-360.jpg",
      "720p": "https://cdn.exercisedb.dev/media/w/images/overhead-press-720.jpg",
    },
    equipments: ["Barbell"],
    bodyParts: ["SHOULDERS"],
    exerciseType: "Strength",
    targetMuscles: ["ANTERIOR DELTOID"],
    secondaryMuscles: ["TRICEPS", "UPPER CHEST", "TRAPEZIUS"],
    videoUrl: "https://cdn.exercisedb.dev/w/videos/overhead-press.mp4",
    keywords: ["overhead", "press", "shoulders", "barbell"],
    overview:
      "The Overhead Press is a compound shoulder exercise that builds upper body pushing strength, targeting the deltoids and triceps.",
    instructions: [
      "Stand with feet shoulder-width apart, barbell at shoulder height.",
      "Grip the bar slightly wider than shoulder-width.",
      "Press the bar overhead until your arms are fully extended.",
      "Lower the bar back to shoulder height with control.",
      "Repeat for the desired number of repetitions.",
    ],
    exerciseTips: [
      "Brace your core to avoid excessive lower back arching.",
      "Tuck your chin as the bar passes your face.",
      "Lock out fully at the top of the movement.",
    ],
    variations: ["Seated Overhead Press", "Dumbbell Shoulder Press", "Push Press"],
    relatedExerciseIds: ["exr_001", "exr_006"],
  },
  {
    exerciseId: "exr_006",
    name: "Barbell Row",
    imageUrl: "https://cdn.exercisedb.dev/media/w/images/barbell-row.jpg",
    imageUrls: {
      "360p": "https://cdn.exercisedb.dev/media/w/images/barbell-row-360.jpg",
      "720p": "https://cdn.exercisedb.dev/media/w/images/barbell-row-720.jpg",
    },
    equipments: ["Barbell"],
    bodyParts: ["BACK"],
    exerciseType: "Strength",
    targetMuscles: ["LATISSIMUS DORSI", "RHOMBOIDS"],
    secondaryMuscles: ["BICEPS", "REAR DELTOID", "TRAPEZIUS"],
    videoUrl: "https://cdn.exercisedb.dev/w/videos/barbell-row.mp4",
    keywords: ["row", "back", "barbell", "pull"],
    overview:
      "The Barbell Row is a compound pulling exercise that targets the upper and mid-back muscles, improving posture and pulling strength.",
    instructions: [
      "Stand with feet hip-width apart, holding a barbell with an overhand grip.",
      "Hinge at the hips until your torso is roughly 45 degrees to the floor.",
      "Pull the barbell towards your lower chest, squeezing your shoulder blades.",
      "Lower the bar back down with control.",
      "Repeat for the desired number of repetitions.",
    ],
    exerciseTips: [
      "Keep your core tight and back flat throughout.",
      "Avoid using momentum to lift the weight.",
      "Focus on squeezing your shoulder blades at the top.",
    ],
    variations: ["Pendlay Row", "Dumbbell Row", "T-Bar Row"],
    relatedExerciseIds: ["exr_003", "exr_004"],
  },
];
